### PR TITLE
small improvement to optimize()

### PR DESCRIPTION
**Pull request by jefemagril**

### CODE REVIEW

**Comment by woodmd** [comment]
This is definitely an improvement over the present logic but I wonder if it might be better to normalize the npred fraction against the sum of all non-skipped sources.  The scenario I'm imagining is that if the skipped sources constitute a large fraction of the total npred then the first fitting step may get skipped entirely.

**Comment by jefemagril** [comment]
Yes, I suppose you are right. I was worried the number of free sources might become too high, but I guess the cap on number of free sources in conjunction works fine to counter that.

**Comment by woodmd** [comment]
On second thought I think this implementation is probably fine -- the intention of the first optimization step was to do a joint fit for the sources that might otherwise bias the fit when normalizations are fit individually.  In that case I think the relevant comparison should be with the fractional amplitude with respect to all components rather than the subset that were not excluded.

If it's ok with you I'll go ahead and merge this PR now.

**Comment by jefemagril** [comment]
Yes, go ahead.

**Pull request merged**
