### PR TITLE
Python 3 print fixes

### PR DESCRIPTION
**Pull request by cdeil**
This PR contains a few Python 3 and PEP8 print fixes. (I did a search and replace from "print " to "print", i.e. remove the space, and added `()` where necessary.)

---

Side comment: using `print` doesn't give users of Fermipy much control and IMO using logging is better (even if it's an extra two lines of boilerplate at the top). In Gammapy we never print, but always emit log messages like this: http://docs.gammapy.org/en/latest/development/howto.html#generating-log-messages

### CODE REVIEW

**Comment by woodmd** [comment]
Thanks for the PR.  For the most part we do use the python logger.  Most of the code you found that uses print statements was added more recently by @eacharles -- at some point we will try to update that to use the same logging conventions as elsewhere in fermipy.  In a few cases I wasn't sure if logging would potentially introduce too much overhead if used in a low-level function.  I guess the pattern to use there is only to instantiate the logger when an exception or error state occurs. Are you doing something like this in gammapy?

**Comment by cdeil** [comment]
> Are you doing something like this in gammapy?

No.

I don't know much about how `logging` works. But presumably loggers only get created on init and it's acceptable if that takes a few extra milliseconds?

**Comment by woodmd** [comment]
To instantiate a logger one would usually call `logging.getLogger`.  This always returns the same logger instance.  However for a low-level function my concern is that the instantiation call might add unnecessary overhead.  Alternatively one could instantiate the logger once and pass it around as a function argument but adding a logger argument to all functions that need logging would result in a lot of boilerplate.  I think the intention was that one calls `getLogger` whenever you need a logger instance so I should probably stick with this approach in fermipy.

**Comment by cdeil** [comment]
What we do in Gammapy is to call
```python
log = logging.getLogger(__name__)
```
at the top of each Python file where log messages are emitted (from most parts of Gammapy, we don't emit any log messages), i.e. loggers only get instantiated at import time:

Explanation: http://docs.gammapy.org/en/latest/development/howto.html#generating-log-messages
Examples: https://github.com/gammapy/gammapy/search?utf8=%E2%9C%93&q=getLogger&type=

I don't remember why, but before deciding on that pattern for Gammapy I did read a bit about Python logging, and Astropy is using the same pattern:
https://github.com/astropy/astropy/search?utf8=%E2%9C%93&q=getlogger&type=

We do have a few explicit classes whose job it is to run checks and log issues. For those, we have a logger attribute on the class, so that callers can configure it and pass in the logger to `__init__`.

**Comment by woodmd** [comment]
Interesting.  That's definitely simpler than the approach we are using.  What are you using to configure the logger?  We have out own logger factory method that creates a logger instance and automatically configures it to pipe log messages to both STDOUT and a common log file.  Is the idea behind the gammapy/astropy approach that the user should partially configure the logger themselves?

**Comment by cdeil** [comment]
>  Is the idea behind the gammapy/astropy approach that the user should partially configure the logger themselves?

Yes, when using Gammapy as a "library", users should configure logging themselves.

Now that we're discussing it, I remember that for the "application" part of Gammapy (i.e. running pre-implemented analyses), it's an open issue how to handle configuration for that: https://github.com/gammapy/gammapy/issues/320

I looked around some more. The module-level logger is the most often recommended pattern to log from libraries: https://docs.python.org/2/howto/logging.html#advanced-logging-tutorial

In the Python cookbook or at http://python-guide-pt-br.readthedocs.io/en/latest/writing/logging/#logging-in-a-library
there's the recommendation to do
```
logging.getLogger(__name__).addHandler(logging.NullHandler())
```
I think the difference between adding a NullHandler or not is what users get if they never configure any logger. With the NullHandler by default nothing is emitted, whereas without it, by default everything WARNING and above will appear. To me it seems reasonable that warnings and errors would appear by default, so I don't see why I would add the NullHandler for the module-level loggers in Gammapy.

**Comment by cdeil** [comment]
What you have now in Fermipy is confusing, no?
https://github.com/fermiPy/fermipy/blob/52f6421cbc6fa40c989f5e2f466d06ce9c4c0935/fermipy/logger.py#L31
The `Logger` class just contains two factory functions for Python loggers and can never be instantiated. On the other hand the `StreamLogger` is a wrapper for a Python logger and can be instantiated.

Probably something to talk about and set up in a good, uniform way in Fermipy and Gammapy next time we meet. :-)

**Comment by woodmd** [comment]
Yea the `Logger` class is probably not so appropriately named (maybe `LoggerFactory` would be better).  This is code I wrote very early on before I knew much about how python logging worked.  Since the user isn't expected to use these classes themselves having a nice and coherent interface didn't seem so critical.  I fully agree that handling logging in some more uniform way would be better so I'm happy to adopt whatever conventions are currently being used in gammapy/astropy.  However since we do want to configure some part of the logging automatically it's not clear that we can just copy the pattern currently used in gammapy.

**Comment by cdeil** [comment]
> Yea the Logger class is probably not so appropriately named (maybe LoggerFactory would be better).

Yes, I think that would be good, to not call something a logger if it's not a Python Logger.

> However since we do want to configure some part of the logging automatically it's not clear that we can just copy the pattern currently used in gammapy.

I wasn't suggesting this. We don't have a good solution yet implemented for logging or configuration in Gammapy.

**Comment by woodmd** [comment]
Ok I guess this discussion got a bit off the original topic.  I opened #137 to remind ourselves that we should revisit how we do logging at some point.  Merging now.

**Pull request merged**
