### PR TITLE
Adding fixed shape lightcurve to correct TS_var

### PR DESCRIPTION
**Pull request by jefemagril**
Introduces new separate lightcurve output from `lightcurve()` which fixes all spectral shape parameters of the source of interest to the previously optimized full-time values. In the dictionary output, these columns have the usual names but with a "`_fixed`" suffix. This was implemented in order to reduce the difference in free parameters between the constant (full-time) fit and the individual time bin fits to 1 (i.e., just the normalization parameter), thereby making TS_var more standardized as a measure of flux variability.

Also of note, changing `minmax_ts=` TS minimums in `_fit_lc()` from 0 to None, because it appears TS values were sometimes negative, and therefore erroneously left out of the fixing/freeing logic.

Added code to improve fitting of bins for the constant and fixed shape lightcurves by fixing very low TS sources.

Now keeps locked params state into lightcurve bins.

### CODE REVIEW

**Comment by kialio** [comment]
It looks like there was an error associated with getting Ubuntu packages.  Not sure if this is the reason the builds are failing:

gpg: requesting key EA312927 from hkp server keyserver.ubuntu.com
gpg: key EA312927: "MongoDB 3.2 Release Signing Key <packaging@mongodb.com>" 1 new signature
gpg: Total number processed: 1
gpg:         new signatures: 1
W: http://dl.hhvm.com/ubuntu/dists/trusty/InRelease: Signature by key 36AEF64D0207E7EEE352D4875A16E7281BE7A449 uses weak digest algorithm (SHA1)
W: The repository 'http://ppa.launchpad.net/couchdb/stable/ubuntu trusty Release' does not have a Release file.
W: Failed to fetch http://ppa.launchpad.net/openjdk-r/ppa/ubuntu/dists/trusty/InRelease  Could not connect to ppa.launchpad.net:80 (91.189.95.83), connection timed out
W: Failed to fetch http://ppa.launchpad.net/pollinate/ppa/ubuntu/dists/trusty/InRelease  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/webupd8team/java/ubuntu/dists/trusty/InRelease  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/chris-lea/redis-server/ubuntu/dists/trusty/main/binary-amd64/Packages  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/chris-lea/redis-server/ubuntu/dists/trusty/main/binary-i386/Packages  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/chris-lea/redis-server/ubuntu/dists/trusty/main/i18n/Translation-en  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/george-edison55/cmake-3.x/ubuntu/dists/trusty/main/binary-amd64/Packages  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/george-edison55/cmake-3.x/ubuntu/dists/trusty/main/binary-i386/Packages  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/george-edison55/cmake-3.x/ubuntu/dists/trusty/main/i18n/Translation-en  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/git-core/ppa/ubuntu/dists/trusty/main/binary-amd64/Packages  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/git-core/ppa/ubuntu/dists/trusty/main/binary-i386/Packages  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/git-core/ppa/ubuntu/dists/trusty/main/i18n/Translation-en  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/main/binary-amd64/Packages  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/main/binary-i386/Packages  Unable to connect to ppa.launchpad.net:http:
W: Some index files failed to download. They have been ignored, or old ones used instead.
git.checkout
1.30s$ git clone --depth=50 https://github.com/fermiPy/fermipy.git fermiPy/fermipy
Cloning into 'fermiPy/fermipy'...
remote: Counting objects: 1024, done.
remote: Compressing objects: 100% (575/575), done.
remote: Total 1024 (delta 515), reused 789 (delta 427), pack-reused 0
Receiving objects: 100% (1024/1024), 7.33 MiB | 19.69 MiB/s, done.
Resolving deltas: 100% (515/515), done.
$ cd fermiPy/fermipy
0.41s$ git fetch origin +refs/pull/163/merge:
remote: Counting objects: 33, done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 33 (delta 24), reused 20 (delta 12), pack-reused 0
Unpacking objects: 100% (33/33), done.
From https://github.com/fermiPy/fermipy
 * branch            refs/pull/163/merge -> FETCH_HEAD
$ git checkout -qf FETCH_HEAD
services
0.02s$ sudo service docker start

**Comment by woodmd** [comment]
Looks like the failures are unrelated to this PR but due to the use of a deprecated method `scipy.stats.chisqprob`.  This error was triggered when the conda defaults channel switched over to scipy 1.0.0.  I'll make a separate PR with a fix.

**Comment by jefemagril** [comment]
Phew! Ok, thanks for tracking that down. I was stumped.

**Comment by woodmd** [comment]
Ok I've made a fix in master with #164 so you'll want to pull that into this branch to fix the test errors.  

On a side note I'd recommend including some explanatory text when you create a PR that briefly describes the goal of the PR and the nature of the changes you're making to the code. Providing a PR description makes it easier for others to review your changes and also serves as a record in case someone wants to go back and figure out why a given change was made.

**Comment by jefemagril** [comment]
Thanks @woodmd. Added some description, and I'll pull this change on Monday.

**Comment by jefemagril** [comment]
I think coveralls failed because our CI tests don't address failed LC bins at all, and that is what the new code is for. I guess we can add a third LC bin for the PG 1553 test that is supposed to fail?

**Pull request merged**
