### PR TITLE
Added assoc flag to delete_sources and get_sources

### PR DESCRIPTION
**Pull request by jefemagril**

### CODE REVIEW

**Comment by woodmd** [comment]
Thanks for the PR.  In principle there's nothing wrong with having an option for deleting unassociated sources but I think a better approach would be to add a parameter that accepts a list of source names, e.g.
```
names = [s.name for s in gta.roi.sources if not s.assoc.get('ASSOC1','')]
gta.delete_sources(names=names)
```
This has the added flexibility of handling more complex selections like deleting unassociated sources with TS < some value.  It also means that the implementation is not tied to column names used in a specific catalog ('ASSOC1' is not defined in 2FHL or 3FHL for instance).

**Comment by woodmd** [comment]
Were you going to amend the PR or should I?  I *think* I have permission to push to your branch if you selected that option when opening the PR but it's not something I've tried before.

**Comment by jefemagril** [comment]
Since you know what you want to do, go right ahead. I think you should be able to, yes.

**Comment by woodmd** [comment]
Merging now.  There are currently no unit tests for this functionality but I ran a few tests on my local installation to verify that the `names` option works as expected.

**Comment by jefemagril** [comment]
Just want to make a slight correction to how this can be implemented using the current schema:
```python
names = [s.name for s in gta.roi.sources if 'ASSOC1' in s.assoc and not s.assoc.get('ASSOC1','')]
gta.delete_sources(names=names)
```

**Pull request merged**
