### PR TITLE
Enable CI tests for dev version of Gammapy

### PR DESCRIPTION
**Pull request by Bultako**
This PR adds a new step in the Github action CI jobs to test `fermipy` with the development version of `gammapy`.
/cc @adonath

### CODE REVIEW

**Review by eacharles — DISMISSED** [review]

**Comment by eacharles** [comment]
Thanks for the fixes

**Comment by henrikef** [comment]
@Bultako we have updated the dependencies to gammapy>=0.18 so some of these changes aren't needed anymore. Could you merge in the changes on the master branch and fix the conflicts?

**Comment by Bultako** [comment]
@henrikef 

Ok done.

**Comment by omodei** [comment]
I think this PS can be close as merges have been done by hands

**Pull request closed without merging**
